#
# Copyright (c) 1992-1998 Michael A. Cooper.  
# This software may be freely used and distributed provided it is not
# sold for profit or used in part or in whole for commercial gain
# without prior written agreement, and the author is credited
# appropriately.
#
# $Id: Makefile.base,v 1.4 1998/11/10 03:39:46 mcooper Exp $
#
# Makefile frontend.
#

RUNMAKE		= ../build/runmake

all clean install install.man bindist: FRC
	@${RUNMAKE} $@

FRC:
