#
# Copyright (c) 1992-1998 Michael A. Cooper.  
# This software may be freely used and distributed provided it is not
# sold for profit or used in part or in whole for commercial gain
# without prior written agreement, and the author is credited
#
# $Id: Makefile,v 6.1 1998/11/10 03:41:58 mcooper Exp $
#

all mf install install.man: FRC

clean:
	rm -f a.out core *~

FRC:
