#
# Copyright (c) 1992-1998 Michael A. Cooper.  
# This software may be freely used and distributed provided it is not
# sold for profit or used in part or in whole for commercial gain
# without prior written agreement, and the author is credited
# appropriately.
#
# $Id: Makefile.real,v 1.2 1998/11/10 04:03:15 mcooper Exp $
#

all doc install install.man: FRC

clean:
	rm -f ${CLEANFILES}

FRC:
